### ISSUE TITLE
Login Error with Meteor 1.6.1

### ISSUE THREAD

**Issue by ulerch** [Garbolino/meteor-accounts-soundcloud#2]
After updating to Meteor version to 1.6.1, I receive the following login error:

Exception while invoking method 'login' Error: Failed to complete OAuth handshake with Soundcloud. Cannot read property 'post' of undefined
    at getAccessToken (packages/nrser_accounts-soundcloud.js:68:11)
    at Object.handleOauthRequest (packages/nrser_accounts-soundcloud.js:33:21)
    at OAuth._requestHandlers.(anonymous function) (packages/oauth2.js:27:31)
    at middleware (packages/oauth.js:203:5)
    at packages/oauth.js:176:5
(oauth.js:431) Error in OAuth Server: Failed to complete OAuth handshake with Soundcloud. Cannot read property 'post' of undefined

The changelog says that "An onExternalLogin hook has been added to the accounts system, to allow the customization of OAuth user profile updates. PR #9042".
